name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew update
      - run: brew tap RouterBase/tap "$GITHUB_WORKSPACE"
      - run: brew audit --strict routerbase
      - run: brew install routerbase
      - run: brew test routerbase
